version: 2

sources:
  - name: staging
    database: ny_taxi
    schema: public
    tables:
      - name: green_tripdata
      - name: yellow_tripdata

models:
  - name: stg_green_tripdata
    columns:
      - name: tripid
        tests:
          - unique
          - not_null

  - name: stg_yellow_tripdata
    columns:
      - name: tripid
        tests:
          - unique
          - not_null

  - name: fact_trips
    columns:
      - name: tripid
        tests:
          - unique
          - not_null
      - name: service_type
        tests:
          - accepted_values:
              values: ['Green', 'Yellow']